version: "3.9"
services:
  backend:
    image: akavire/backend:lattest
    ports:
      - "8000:8000"
    container_name: "backend"
    command: ./entrypoint.sh
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
    networks:
      - application
  mysql:
    image: mysql:8.0
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - application

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin"
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      application:
        aliases:
          - phpmyadmin

networks:
  application:
    driver: bridge

volumes:
  mysql:
